location                 = "uksouth"
dns_zone_name            = "lab-hmcts.net"
dns_zone_rg_name         = "lab-dns"
common_name              = "test.lab-hmcts.net"
key_vault_name           = "KV-LAB-TFE-01"
key_vault_resource_group = "RG-LAB-TFE-01"
cert_name                = "test-lab-hmcts-net"
letsencrypt_hostname     = "acme-staging-v02"
