location                 = "uksouth"
dns_zone_name            = "megaloop.world"
dns_zone_rg_name         = "lab-dns"
common_name              = "test.megaloop.world"
key_vault_name           = "KV-LAB-TFE-01"
key_vault_resource_group = "RG-LAB-TFE-01"
cert_name                = "test-cert"
